name: "Release Pipeline"
on:
  create: { tag }
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - uses: actions/checkout@v2.3.4

      - name: "Get tag name"
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
          architecture: x64

      - name: "Set labels for ${{ github.ref }}"
        run: |
          echo "PASETO_TAG_VERSION=${{ steps.tag.outputs.tag }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: |
          mvn versions:set -DnewVersion=${{ env.PASETO_MAVEN_VERSION }}
          mvn clean install -DskipTests

      - name: "Create release"
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            version1/**.jar
            version2/**.jar
          body: |
            ## Version ${{ steps.tag.outputs.tag }}

            ### New functionality

            - Moved to using Tuweni library instead of Cava
            - Moved to Maven
            - Update libaries which were marked by dependabot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  new_version:
    name: Update to next snapshot version
    needs: [ release ]
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          architecture: x64

      - name: Set version to next snapshot
        run: |
          mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit

      - name: Commit pom.xml
        run: |
          git config user.name Nanne Baars
          git config user.email nanneb@gmail.com
          find . -name 'pom.xml' | xargs git add
          git commit -m "Updating to the new snapshot version"
          git push
